name: Download Google Drive

on:
  workflow_dispatch:

jobs:
  download:

    runs-on: ubuntu-latest

    steps:

    - name: Clonar repositório
      uses: actions/checkout@v4

    - name: Instalar Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar script
      run: python baixar_drive.py

    - name: Salvar arquivos baixados
      uses: actions/upload-artifact@v4
      with:
        name: arquivos_baixados
        path: downloads/
